### ISSUE TITLE
Document advantages over fluent-kubernetes-daemonset

### ISSUE THREAD

**Issue by dileepfrog** [fluent/fluent-bit-kubernetes-daemonset#4]
This project looks like a very neat lightweight edition of the full-blown fluentd agent, just curious about specific use cases for choosing one over the other.

**Comment by edsiper** [comment]
@dileepfrog 

Fluent Bit is a lightweight log forwarder that is part of Fluentd Ecosystem. In the last months we have get many request to implement several features that is making an alternative to Fluentd in Kubernetes ecosystem for certain scenarios:

- Fluent Bit deployed as a daemonset and use Fluentd's as aggregators
- Fluent Bit sending logs to Elasticsearch or InfluxDB backends

Fluentd is more flexible in terms of filters and general plugins (more than 700 available), so if you have Kafka, Loggly or Stackdriver as backend you will go with Fluentd. Otherwise Fluent Bit is a good alternative to reduce the resources from your cluster.

**Comment by edsiper** [comment]
Closing as fixed.
